// <auto-generated />
using System;
using Chiro.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chiro.Infra.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240703020156_CriacaoCampoCreationDateNoProject")]
    partial class CriacaoCampoCreationDateNoProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chiro.Domain.Entities.AuthenticationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationTokens");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.BoardAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AdjustedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BoardActionType")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConcludedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimelineRow")
                        .HasColumnType("integer");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BoardActions");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.BoardActionLink", b =>
                {
                    b.Property<long>("BaseBoardActionId")
                        .HasColumnType("bigint");

                    b.Property<long>("LinkedBoardActionId")
                        .HasColumnType("bigint");

                    b.HasKey("BaseBoardActionId", "LinkedBoardActionId");

                    b.HasIndex("LinkedBoardActionId");

                    b.ToTable("BoardActionLinks");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.BoardAction", b =>
                {
                    b.HasOne("Chiro.Domain.Entities.Project", "Project")
                        .WithMany("BoardActions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.BoardActionLink", b =>
                {
                    b.HasOne("Chiro.Domain.Entities.BoardAction", "BaseBoardAction")
                        .WithMany("BoardActionLinks")
                        .HasForeignKey("BaseBoardActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chiro.Domain.Entities.BoardAction", "LinkedBoardAction")
                        .WithMany()
                        .HasForeignKey("LinkedBoardActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseBoardAction");

                    b.Navigation("LinkedBoardAction");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.BoardAction", b =>
                {
                    b.Navigation("BoardActionLinks");
                });

            modelBuilder.Entity("Chiro.Domain.Entities.Project", b =>
                {
                    b.Navigation("BoardActions");
                });
#pragma warning restore 612, 618
        }
    }
}
